### ISSUE TITLE
W-11 — Theme 配置契约与序列选择逻辑收敛

### ISSUE THREAD

**Issue by kaiqiangh** [kaiqiangh/market-risk-dashboard#243]
## Problem

Theme configuration currently accepts semantically invalid proxy shapes and duplicates the ETF-versus-basket predicate in the collector and the symbol-health gate. A bad proxy can silently produce an empty theme series, while the duplicated predicate can drift. Duplicate constituents are also accepted and can leak duplicate symbols into published theme rows.

## Scope

- Validate `ThemeProxy`: `kind: etf` requires a non-empty symbol; `kind: basket` must not carry a symbol.
- Reject duplicate constituent symbols within each `ThemeDef`.
- Centralize theme history-symbol selection and ETF series-symbol selection in the config model layer; reuse them from `MarketCollector` and `symbol_health`.
- Preserve valid `config/themes.yaml` behavior and published payload shape.

## Acceptance criteria

- Invalid ETF/basket proxy combinations fail at `Settings.load_themes_config()` with `ConfigError`.
- Duplicate constituent symbols fail at config load with an actionable theme-specific error.
- Collector and symbol-health gate use the same shared selection helper; no duplicated proxy predicate remains.
- Existing valid config and theme calculations remain unchanged.
- Focused regression tests cover both invalid proxy shapes, duplicate constituents, and shared helper behavior.
- No new dependency, document, or broad module split.

## Verification

Run focused config/market/symbol-health tests, then the full local and remote repository gates before closing.

**Comment by kaiqiangh** [comment]
PASS

Code review for commit `845b9cf` against `a82c0f9`: no actionable defects found.

Verified:
- `ThemeProxy` rejects an ETF without a symbol and a basket with a symbol at config validation;
- each `ThemeDef` rejects duplicate constituent symbols;
- `theme_history_symbols` and `ThemeDef.series_symbol` centralize the ETF/basket selection semantics used by the collector and symbol-health gate;
- valid `config/themes.yaml` behavior and published payload shape remain unchanged;
- focused config/market/symbol-health tests passed, full pipeline tests (672) passed, and the touched-file Ruff checks passed;
- remote Test Pipeline `33696146827`, Deploy Pages `33696146840`, PR Validate Data `33696146473`, and PR Test Pipeline `33696146461` all passed.

No broad module split or new dependency was introduced.
